### ISSUE TITLE
Sample Request: Home Assistant entity into Vestaboard service

### ISSUE THREAD

**Issue by davethetallguy** [DanielBaulig/vestaboard#4]
Your description mentions using HA to post various events to your Vestaboard. I'm having difficulty getting json variables properly formatted so the service accepts them.

Could you give an example of posting from a sensor, such as: 
         Temperature: xx 
where xx is the value of sensor.temperature ? 

I've tried various template combinations unsuccessfully including the one I thought was likely:
- Temperature: {{sensor.temperature.state}}

**Comment by DanielBaulig** [comment]
I assume you are talking about sending your own requests to Vestaboard, not using this integration, right?

Vestaboard takes a special non-standard proprietary character encoding. There’s a table that shows which byte values map to which characters in their developer documentation.You can also checkout this post of mine in the Home Assistant forums. It has a RESTful based version of the Vestaboard API Implantation that also defines a map that you can use to encode any string to the Vestaboard encoding using Jinja templates:

https://community.home-assistant.io/t/vestaboard-integration/402932/1

**Comment by DanielBaulig** [comment]
Just in case you were asking how to use this integration vs writing your own custom solution, I've just added an example usage in the README.md

**Comment by davethetallguy** [comment]
Thanks, the sample helped, and the pointer to the message string was even more instructive. I've ended up with my own script based on both your examples and Flaker's. 

My goal was to display current and forecast weather data from my Weatherflow Tempest, and it's looking pretty promising already.
